# Generated by Django 3.2.3 on 2021-06-25 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('mobile', models.IntegerField(null=True)),
                ('dob', models.DateField(null=True)),
                ('doj', models.DateField(default=datetime.date.today)),
                ('department', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
