# Generated by Django 3.2.3 on 2021-06-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('INTERNS', 'INTERNS'), ('BACKEND_DEVELOPER', 'BACKEND_DEVELOPER'), ('FRONTEND_DEVELOPER', 'FRONTEND_DEVELOPER'), ('DESIGNER', 'DESIGNER'), ('HR', 'HR'), ('MARKETING', 'MARKETING'), ('ADMINISTRATOR', 'ADMINISTRATOR')], default='INTERNS', max_length=50),
        ),
    ]
